version: "2"
run:
  modules-download-mode: readonly
  allow-parallel-runners: true

linters:
  enable:
    - revive
    - govet
    - staticcheck
  settings:
    revive:
      rules:
        - name: context-keys-type
        - name: time-naming
        - name: var-declaration
        - name: unexported-return
        - name: errorf
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: var-naming
          arguments:
            - - ID
              - IP
              - JSON
              - URL
              - HTTP
              - SQL
              - CPU
              - URI
            - [ ]
            - - skipPackageNameChecks: true
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
        - name: unreachable-code
    staticcheck:
      checks: [ "all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022","-ST1012" ]
  exclusions:
    generated: lax
    paths:
      - examples
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - examples
