name: compatibility

on:
  pull_request:
    branches:
      - '3.1'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        td_version: ['main', '3.0']
    name: Build ${{ matrix.td_version }}
    steps:
      - name: Setup TDengine nightly
        uses: ./.github/actions/setup-tdengine
        with:
          mode: 'nightly'
          branch: ${{ steps.get-branch.outputs.branch }}
          start-services: 'true'
          nightly-url: ${{ secrets.NIGHTLY_TDENGINE_ENTERPRISE_BASE_URL }}

  test:
    runs-on: ubuntu-22.04
    needs: build
    strategy:
      matrix:
        go: ['1.14', '1.17', '1.22', 'stable']
        td_version: ['main', '3.0']
    name: Go ${{ matrix.td_version }} ${{ matrix.go }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Cache server
        uses: actions/cache@v5
        with:
          path: server.tar.gz
          key: ${{ runner.os }}-build-${{ matrix.td_version }}-${{ needs.build.outputs.commit_id }}
          restore-keys: |
            ${{ runner.os }}-build-${{ matrix.td_version }}-

      - name: Install dependencies
        run: sudo apt install -y libgeos-dev

      - name: Setup TDengine from build
        uses: ./.github/actions/setup-tdengine
        with:
          mode: 'build'
          commit-id: ${{ needs.build.outputs.commit_id }}
          event-key: ${{ matrix.td_version }}

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go }}
          cache-dependency-path: go.sum

      - name: Test
        run: |
          packages="./..."
          if [ "${{ matrix.go }}" = "1.14" ] || [ "${{ matrix.go }}" = "1.17" ]; then
            packages="$(go list ./... | grep -v '^github.com/taosdata/driver-go/v3/examples/')"
          fi
          sudo go test -v --count=1 -coverprofile=coverage.txt -covermode=atomic $packages
